[book]
authors = ["Rafael Lúcio"]
language = "pt-br"
multilingual = true
src = "docs/src"
title = "CET961 - Engenharia Assistida por Computador"

[output.html]
default-theme = "light"
preferred-dark-theme = "rust"
additional-css = ["docs/css/rust_book_style.css"]
git-repository-url = "https://github.com/Azgrom/CAE"

[output.html.search]
limit-results = 15

[preprocessor.katex]
