[book]
authors = ["Rafael Lúcio"]
language = "en"
multilingual = false
src = "src"
title = "CET961 - Engenharia Assistida por Computador"

[output.html]
additional-css = ["css/2018-edition.css"]


[preprocessor.katex]
